# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "generic/ubuntu1804"
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network "private_network", ip: "192.168.10.2"
    k8smaster.vm.provider "parallels" do |prl|
      prl.memory = 6144
      prl.cpus = 3
    end
    k8smaster.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 3
    end
    k8smaster.vm.provider "vmware_fusion" do |v|
      v.memory = 6144
      v.cpus = 3
    end
    k8smaster.vm.provision "shell", path: "provision-master.sh"
  end

  config.vm.define "k8sworker1" do |k8sworker1|
    k8sworker1.vm.box = "generic/ubuntu1804"
    k8sworker1.vm.hostname = "k8sworker1"
    k8sworker1.vm.network "private_network", ip: "192.168.10.3"
    k8sworker1.vm.provider "parallels" do |prl|
      prl.memory = 6144
      prl.cpus = 2
    end
    k8sworker1.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 2
    end
    k8sworker1.vm.provider "vmware_fusion" do |v|
      v.memory = 6144
      v.cpus = 2
    end
    k8sworker1.vm.provision "shell", path: "provision-worker.sh"
  end

  config.vm.box_check_update = false
  config.vm.provision "shell", path: "provision.sh"
end
