# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "generic/ubuntu1804"
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network "private_network", ip: "192.168.10.2"
    k8smaster.vm.provider "parallels" do |prl|
      prl.memory = 6144
      prl.cpus = 3
    end
    k8smaster.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 3
    end
    k8smaster.vm.provider "vmware_fusion" do |v|
      v.memory = 6144
      v.cpus = 3
    end
    k8smaster.vm.provision "shell", path: "provision-master.sh"
  end
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "provision.sh"
end
